DRAW_DEBUGS = False

# game constants
BACKGROUND_PERLIN_RANGE = (0, 20)
BACKGROUND_PERLIN_SPEED = 0.1
EXCITEMENT_DECAY = 0.97

# line constants
LINE_DEFAULT_STROKE = 3
LINE_PERLIN_SPEED = 0.02
LINE_PERLIN_XRATIO = 0.005
LINE_PERLIN_YRANGE_RATIO = 0.3
LINE_ALPHA = 150
LINE_XSTEP = 50

# paddle constants
PADDLE_DEFAULT_STROKE = 5
PADDLE_DEFAULT_WIDTH = 150
PADDLE_DEFAULT_HEIGHT = 15
PADDLE_MOVEMENT_STEP = 8
PADDLE_DEFAULT_DISTANCE = 5
PADDLE_DEFAULT_OFFSET = PADDLE_DEFAULT_HEIGHT * 0.5 + PADDLE_DEFAULT_DISTANCE

# neon colouring constants
NEON_FILL_LERP_RATIO_RANGE = (0.6, 0.8)
NEON_COLOUR_PERLIN_SPEED = 0.1

# ball constants
BALL_DEFAULT_STROKE = 2
BALL_DEFAULT_RADIUS = 7
BALL_DEFAULT_ANGLE = HALF_PI
BALL_START_ABBERATION_RANGE = (0.05, 0.1)
BALL_DEFAULT_SPEED = 8
BALL_MAX_REFLECT_MAG = HALF_PI * 0.6
BALL_PERLIN_SPEED = 0.06
BALL_PERLIN_RANGE = (0.8, 1 / 0.8)

COLLISION_FUZZ = (PADDLE_DEFAULT_STROKE + BALL_DEFAULT_STROKE) * 0.5

# perlin variate constants
PERLIN_START_RANGE = 10

# more general definitions
WHITE = color(255)

class GameOver(Exception):
    pass

class Collision(Exception):
    pass